//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_SS3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WSC2019_SS3Entities : DbContext
    {
        public WSC2019_SS3Entities()
            : base("name=WSC2019_SS3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssetOdometer> AssetOdometers { get; set; }
        public virtual DbSet<Asset> Assets { get; set; }
        public virtual DbSet<PMScheduleModel> PMScheduleModels { get; set; }
        public virtual DbSet<PMScheduleType> PMScheduleTypes { get; set; }
        public virtual DbSet<PMTask> PMTasks { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
    }
}
