//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_SS3
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMScheduleModel
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> PMScheduleTypeID { get; set; }
    
        public virtual PMScheduleType PMScheduleType { get; set; }
    }
}
