//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_SS3
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMTask
    {
        public int ID { get; set; }
        public Nullable<int> AssetID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> PMScheduleTypeID { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<int> ScheduleKilometer { get; set; }
        public Nullable<bool> TaskDone { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual PMScheduleType PMScheduleType { get; set; }
        public virtual Task Task { get; set; }
    }
}
