//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_SS1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset()
        {
            this.AssetPhotos = new HashSet<AssetPhoto>();
        }
    
        public int ID { get; set; }
        public string AssetSN { get; set; }
        public string AssetName { get; set; }
        public string Description { get; set; }
        public Nullable<int> WarrantyDate { get; set; }
        public Nullable<int> DepartmentLocationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> AssetGroupID { get; set; }
    
        public virtual AssetGroup AssetGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetPhoto> AssetPhotos { get; set; }
        public virtual DepartmentLocation DepartmentLocation { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
