//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_SS1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetTransferLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetTransferLog()
        {
            this.AssetTransferLogs1 = new HashSet<AssetTransferLog>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AssetID { get; set; }
        public string FromAssetSN { get; set; }
        public string ToAssetSN { get; set; }
        public Nullable<int> FromDepartmentLocationID { get; set; }
        public Nullable<int> ToDepartmentLocationID { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetTransferLog> AssetTransferLogs1 { get; set; }
        public virtual AssetTransferLog AssetTransferLog1 { get; set; }
        public virtual DepartmentLocation DepartmentLocation { get; set; }
        public virtual DepartmentLocation DepartmentLocation1 { get; set; }
    }
}
